### PR TITLE
feat: add CM6 support

### PR DESCRIPTION
**Pull request by gcusnieux**
Hi;
I would like to use the library with CM6, 
I propose this migration which consists simply to manage the files in the same way as https://github.com/codemirror/legacy-modes

### CODE REVIEW

**Comment by nerk** [comment]
@gcusnieux Thanks for your contribution.

**Comment by gcusnieux** [comment]
You're welcome,
Do you have time to publish a tag on npm ?

**Comment by nerk** [comment]
I'm planning to do so, but I am a bit busy right now. This is the one and only package I ever published to npmjs 5 years ago. I'll have to check how to do it, can't remember. ;-)

**Comment by nerk** [comment]
@gcusnieux It's published.

**Comment by gcusnieux** [comment]
Thx @nerk

**Pull request merged**
